%#codegen

function [M,Tsfc,Lin,LinZ,Lout,sensible,latent,G,opt_out]=...
codegen_ebalance(Lin_coarse,q_coarse,Zdiff,T_coarse,T_fine,Vf,...
albedo,Sin,windspd,pres_coarse,pres_fine,mode,tau,cc)

[M,Tsfc,Lin,LinZ,Lout,sensible,latent,G,opt_out]=...
solve_ebalance(Lin_coarse,q_coarse,Zdiff,T_coarse,T_fine,Vf,...
albedo,Sin,windspd,pres_coarse,pres_fine,mode,tau,cc);

end