downscale_energy_azure(183,...
    '/Users/nbair/Desktop/recon_inputs/fsca/Sierra_MODSCAG_500m_albers_2013.h5',...
    '/Users/nbair/Desktop/recon_inputs/topo/Sierra_Topography_500m_albers.h5',...
    '/Users/nbair/Desktop/recon_inputs/landcover/Sierra_landcover_500m_albers.h5',...
    '/Users/nbair/Desktop/recon_inputs/nldas/primary_forcing',...
    '/Users/nbair/Desktop/recon_inputs/nldas/DEM/nldas_topo.h5',...
    '/Users/nbair/Desktop/energy');