set COMPILER=gcc
				set COMPFLAGS=-c -fexceptions -fno-omit-frame-pointer -DMATLAB_MEX_FILE  -DMATLAB_MEX_FILE  
				set OPTIMFLAGS=-O -DNDEBUG 
				set DEBUGFLAGS=-g 
				set LINKER=gcc 
				set LINKFLAGS=-m64 -Wl,--no-undefined -shared -L"C:\Program Files\MATLAB\R2016b\extern\lib\win64\mingw64" -llibmx -llibmex -llibmat -lm -llibmwlapack -llibmwblas  
				set LINKDEBUGFLAGS=-g
				set NAME_OUTPUT=-o "%OUTDIR%%MEX_NAME%%MEX_EXT%"
set PATH=C:\raid\bin\TDM-GCC\bin;C:\Program Files\MATLAB\R2016b\extern\include\win64;C:\Program Files\MATLAB\R2016b\extern\include;C:\Program Files\MATLAB\R2016b\simulink\include;C:\Program Files\MATLAB\R2016b\lib\win64;%MATLAB_BIN%;%PATH%
set INCLUDE=%MW_MINGW64_LOC%\include;;%INCLUDE%
set LIB=%MW_MINGW64_LOC%\lib;;%LIB%
set LIBPATH=C:\Program Files\MATLAB\R2016b\extern\lib\win64;%LIBPATH%
